### ISSUE TITLE
won't start in hassio maybe a parsing issue?

### ISSUE THREAD

**Issue by JamesOsborn-SE** [rhasspy/rhasspy-junior#2]
Log snippit: 

```
DEBUG:rhasspy_junior.intent.intent_fsticuffs.ini_jsgf:Loaded ini file
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/app/rhasspy_junior/train/__main__.py", line 63, in <module>
    main()
  File "/app/rhasspy_junior/train/__main__.py", line 59, in main
    train.run(context)
  File "/app/rhasspy_junior/train/multi_trainer.py", line 49, in run
    context = trainer.run(context)
  File "/app/rhasspy_junior/train/fsticuffs.py", line 65, in run
    if self.train_intent():
  File "/app/rhasspy_junior/train/fsticuffs.py", line 124, in train_intent
    intents = parse_ini(ini_text)
  File "/app/rhasspy_junior/intent/intent_fsticuffs/ini_jsgf.py", line 121, in parse_ini
    Sentence.parse(
  File "/app/rhasspy_junior/intent/intent_fsticuffs/jsgf.py", line 136, in parse
    parse_expression(s, text, metadata=metadata)
  File "/app/rhasspy_junior/intent/intent_fsticuffs/jsgf.py", line 499, in parse_expression
    end_index = parse_expression(
  File "/app/rhasspy_junior/intent/intent_fsticuffs/jsgf.py", line 519, in parse_expression
    end_index = parse_expression(
  File "/app/rhasspy_junior/intent/intent_fsticuffs/jsgf.py", line 574, in parse_expression
    end_index = parse_expression(
  File "/app/rhasspy_junior/intent/intent_fsticuffs/jsgf.py", line 434, in parse_expression
    assert last_group is not None, parse_error(
AssertionError: No group preceeding literal (text='name:Catbox: Electric Consumed [kWh\]} state :{entity_id:sensor.catbox_electric_consumed_kwh}', file=<StringIO>, column=31, line=32)
```

**Comment by synesthesiam** [comment]
Ah, yes! This is two escape systems fighting with each other. I should be able to fix this quickly...

**Comment by synesthesiam** [comment]
OK, give version 0.2.2 a try and see if that helps :+1:

**Comment by JamesOsborn-SE** [comment]
Progress!
I don't get that error anymore.. I got a new error 
```
DEBUG:rhasspy_junior.loop:Empty audio chunk from microphone. Exiting
```

**Comment by synesthesiam** [comment]
Yay for progress! Is your mic selectable from the drop down menu in the Rhasspy HA add-on page?
